### ISSUE TITLE
Small template update

### ISSUE THREAD

**Issue by usernolan** [CoNarrative/precept-template#2]
_Following contribution guidelines; apologies if opening an issue is overkill._

A fresh

    lein new precept <proj>

is unable to compile with [org.clojure/clojurescript "1.9.854"] (latest) unless the following changes are also made to project.clj:

    ;; line 7 should be 
    [precept "0.4.0-alpha"]

    ;; line 25 should be 
    [figwheel-sidecar "0.5.11"]
   
    ;; line 28 should be 
    :plugins      [[lein-figwheel "0.5.11"]]

pull request to come.

**Comment by Nolan330** [comment]
#3 PR'd

**Comment by alex-dixon** [comment]
Definitely not overkill. Really appreciate your contribution. Reviewing the PR now.
